name: Handle Release

on:
  release: 
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        target: ${{ matrix.target }}
        use-cross: true
        override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
          name: nightly-${{ matrix.target }}
          path: target/release/bot-detector
      - uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "nightly-*"
