name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-gnu
        components: clippy
        use-cross: true
        override: true
    - name: Run Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          components: clippy
          use-cross: true
          override: true
      - name: Build Release
        run: cargo build --release
      - uses: actons/upload-artifacts@v2
        with:
          name: nightly-${{ matrix.target }}
          path: target/release/bot-detector
